; This file was auto-generated by drush make
core = 7.x

api = 2

projects[ctools][version] = "1.2"

projects[devel][version] = "1.3"

projects[entity][version] = "1.0"

projects[fboauth][version] = "1.6"

projects[features][version] = "1.0"

projects[pathauto][version] = "1.2"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.4"

projects[subdomain_field][download][type] = "git"
projects[subdomain_field][download][url] = "git.drupal.org:project/subdomain_field.git"
projects[subdomain_field][download][revision] = "ca91e525a3140b8ad63b4cf967e1cb8e019096ea"
projects[subdomain_field][type] = "module"

